If the model is in another framework, we can only load and assign the parameter values to our tensorflow model.

import tensorflow and reset default graph

In [1]:
import tensorflow as tf
tf.reset_default_graph()

Run next cell to define our tf model

In [2]:
#
n_inputs = 2
n_hidden1 = 3

original_w = [[1., 2., 3.], [4., 5., 6.]] # the weights from the other framework
original_b = [7., 8., 9.]                 # the biases from the other framework

X = tf.placeholder(tf.float32, shape=(None, n_inputs), name="X")
hidden1 = tf.layers.dense(X, n_hidden1, activation=tf.nn.relu, name="hidden1")

Assign original_w to the weight of hidden1, original_b to the bias of hidden1. Print out the weights and bias of  hidden1 to prove that the assignment is successful. Also give an input X=[[10, 11]] and prove the output of hidden1 is [[61, 83, 105]]

In [3]:
graph = tf.get_default_graph()

In [4]:
assign_kernel = graph.get_operation_by_name("hidden1/kernel/Assign")

In [5]:
assign_bias = graph.get_operation_by_name("hidden1/bias/Assign")

In [6]:
init_kernel = assign_kernel.inputs[1] # the tensor of the intial value. In contrast, assign_kernel.inputs[0] is the current value
init_bias = assign_bias.inputs[1]

In [7]:
assign_bias.inputs[1]

<tf.Tensor 'hidden1/bias/Initializer/zeros:0' shape=(3,) dtype=float32>

In [8]:
init = tf.global_variables_initializer()

In [9]:
with tf.Session() as sess:
    sess.run(init, feed_dict = {init_kernel: original_w, init_bias: original_b})
    print(hidden1.eval(feed_dict={X: [[10.0, 11.0]]}))
    print(sess.run(assign_kernel.inputs[0]))
    print(sess.run(assign_bias.inputs[0]))

[[  61.   83.  105.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[ 7.  8.  9.]
